##on:
##  push:
##    tags:
##      # See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
##      - 'v[0-9].[0-9]*'

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump event JSON
        env:
          EVENT_JSON_FILENAME: ${{ github.event_path }}
        run: cat "$EVENT_JSON_FILENAME"

      - name: Tag check
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "TAG v"

      - name: Tag check
        if: startsWith(github.ref, 'refs/tags/v*')
        run: |
          echo "TAG v*"

      - name: Tag check
        if: startsWith(github.ref, 'refs/tags/v*.*')
        run: |
          echo "TAG v*.*"

      - name: Tag check
        if: startsWith(github.ref, 'refs/tags/v*.**')
        run: |
          echo "TAG v*.**"

      - name: Set env
        run: |
          echo "GITHUB_REF=${GITHUB_REF}"
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
